id: I0888EE6B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:00:33+00:00'
last_modified: '2022-06-08T05:30:11.601044+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7561
  title: གྲུབ་ཆེན་ཐང་སྟོང་རྒྱལ་པོ་དང་འབྲེལ་བའི་བླ་མའི་རྣལ་འབྱོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6A3C:
      image_group_id: I3CN7563
      title: ''
      total_pages: 42
      order: 1
      base_file: 6A3C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
