id: I0888EE6B
legacy_id: P005642
ocr_import_info:
  bdrc_scan_id: W3CN7561
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T03:00:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:42:04.848273+00:00'
last_modified: 2022-09-03 23:42:09.119056
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7561
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7561
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་ཆེན་ཐང་སྟོང་རྒྱལ་པོ་དང་འབྲེལ་བའི་བླ་མའི་རྣལ་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.952560656006981
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN7563:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7563
      total_pages: 42
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7563.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.952560656006981
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
