id: P005642
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN7561
  title: གྲུབ་ཆེན་ཐང་སྟོང་རྒྱལ་པོ་དང་འབྲེལ་བའི་བླ་མའི་རྣལ་འབྱོར།
  author: ''
  volumes:
    bc8a05e96819487ba650bf1148f110c2:
      image_group_id: I3CN7563
      title: ''
      volume_number: 1
      total_pages: 42
      base_file: v001.txt
